"""Initial migration: Create all tables from MySQL schema

Revision ID: 531132e5ec92
Revises: 
Create Date: 2026-01-02 02:02:39.734874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '531132e5ec92'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('m_caste',
    sa.Column('caste_id', sa.Integer(), nullable=False),
    sa.Column('caste_name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('caste_id')
    )
    op.create_index(op.f('ix_m_caste_caste_id'), 'm_caste', ['caste_id'], unique=False)
    op.create_table('m_gallery_category',
    sa.Column('gal_cat_id', sa.Integer(), nullable=False),
    sa.Column('gal_cat_name', sa.String(length=20), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('gal_cat_id')
    )
    op.create_index(op.f('ix_m_gallery_category_gal_cat_id'), 'm_gallery_category', ['gal_cat_id'], unique=False)
    op.create_table('m_news_category',
    sa.Column('news_cat_id', sa.Integer(), nullable=False),
    sa.Column('news_cat_name', sa.String(length=50), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('news_cat_id')
    )
    op.create_index(op.f('ix_m_news_category_news_cat_id'), 'm_news_category', ['news_cat_id'], unique=False)
    op.create_table('m_qualification',
    sa.Column('qualification_id', sa.Integer(), nullable=False),
    sa.Column('qualification_name', sa.String(length=50), nullable=False),
    sa.Column('qual_code', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('qualification_id')
    )
    op.create_index(op.f('ix_m_qualification_qualification_id'), 'm_qualification', ['qualification_id'], unique=False)
    op.create_table('m_role',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('role_id')
    )
    op.create_index(op.f('ix_m_role_role_id'), 'm_role', ['role_id'], unique=False)
    op.create_table('m_state',
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.Column('state_name', sa.String(length=30), nullable=False),
    sa.Column('state_code', sa.String(length=4), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('state_id')
    )
    op.create_index(op.f('ix_m_state_state_id'), 'm_state', ['state_id'], unique=False)
    op.create_table('m_stream',
    sa.Column('stream_id', sa.Integer(), nullable=False),
    sa.Column('stream_name', sa.String(length=100), nullable=False),
    sa.Column('qual_code', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('stream_id')
    )
    op.create_index(op.f('ix_m_stream_stream_id'), 'm_stream', ['stream_id'], unique=False)
    op.create_table('user_otp_track',
    sa.Column('otp_id', sa.Integer(), nullable=False),
    sa.Column('otp_data', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('otp_id')
    )
    op.create_index(op.f('ix_user_otp_track_email'), 'user_otp_track', ['email'], unique=False)
    op.create_index(op.f('ix_user_otp_track_otp_id'), 'user_otp_track', ['otp_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('APPLICANT', 'CENTRE', 'ADMIN', name='roleenum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('applicant_id', sa.Integer(), nullable=True),
    sa.Column('center_id', sa.Integer(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_applicant_id'), 'users', ['applicant_id'], unique=False)
    op.create_index(op.f('ix_users_center_id'), 'users', ['center_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_employee_id'), 'users', ['employee_id'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('m_college',
    sa.Column('college_id', sa.Integer(), nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.Column('college_name', sa.String(length=150), nullable=False),
    sa.ForeignKeyConstraint(['state_id'], ['m_state.state_id'], ),
    sa.PrimaryKeyConstraint('college_id')
    )
    op.create_index(op.f('ix_m_college_college_id'), 'm_college', ['college_id'], unique=False)
    op.create_table('m_district',
    sa.Column('district_id', sa.Integer(), nullable=False),
    sa.Column('district_name', sa.String(length=30), nullable=False),
    sa.Column('district_code', sa.String(length=10), nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['state_id'], ['m_state.state_id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('district_id'),
    sa.UniqueConstraint('state_id', 'district_id', name='m_district_state_id_district_id_uniq')
    )
    op.create_index(op.f('ix_m_district_district_id'), 'm_district', ['district_id'], unique=False)
    op.create_table('m_applicant',
    sa.Column('applicant_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=False),
    sa.Column('middle_name', sa.String(length=30), nullable=False),
    sa.Column('last_name', sa.String(length=30), nullable=False),
    sa.Column('father_name', sa.String(length=50), nullable=False),
    sa.Column('gender', sa.String(length=1), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('caste_id', sa.Integer(), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=False),
    sa.Column('pin_code', sa.Integer(), nullable=False),
    sa.Column('college_id', sa.Integer(), nullable=False),
    sa.Column('other_college', sa.String(length=60), nullable=True),
    sa.Column('email_id', sa.String(length=100), nullable=False),
    sa.Column('mobile_no', sa.String(length=10), nullable=False),
    sa.Column('profile_photo', sa.String(length=100), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=False),
    sa.Column('pass', sa.String(length=255), nullable=True),
    sa.Column('active_status', sa.String(length=1), nullable=False),
    sa.ForeignKeyConstraint(['caste_id'], ['m_caste.caste_id'], ),
    sa.ForeignKeyConstraint(['college_id'], ['m_college.college_id'], ),
    sa.ForeignKeyConstraint(['district_id'], ['m_district.district_id'], ),
    sa.ForeignKeyConstraint(['state_id'], ['m_state.state_id'], ),
    sa.PrimaryKeyConstraint('applicant_id')
    )
    op.create_index(op.f('ix_m_applicant_applicant_id'), 'm_applicant', ['applicant_id'], unique=False)
    op.create_index(op.f('ix_m_applicant_email_id'), 'm_applicant', ['email_id'], unique=True)
    op.create_table('m_center',
    sa.Column('center_id', sa.Integer(), nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=False),
    sa.Column('center_name', sa.String(length=100), nullable=False),
    sa.Column('center_code', sa.String(length=10), nullable=True),
    sa.Column('center_address', sa.Text(), nullable=True),
    sa.Column('center_phone', sa.String(length=15), nullable=True),
    sa.Column('center_mail_id', sa.String(length=50), nullable=True),
    sa.Column('center_pay_link', sa.String(length=255), nullable=True),
    sa.Column('center_venue', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['district_id'], ['m_district.district_id'], ),
    sa.ForeignKeyConstraint(['state_id'], ['m_state.state_id'], ),
    sa.PrimaryKeyConstraint('center_id'),
    sa.UniqueConstraint('center_phone')
    )
    op.create_index(op.f('ix_m_center_center_id'), 'm_center', ['center_id'], unique=False)
    op.create_table('m_employee',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('emp_first_name', sa.String(length=30), nullable=False),
    sa.Column('emp_middle_name', sa.String(length=30), nullable=True),
    sa.Column('emp_last_name', sa.String(length=30), nullable=False),
    sa.Column('emp_jod', sa.Date(), nullable=False),
    sa.Column('emp_dob', sa.Date(), nullable=True),
    sa.Column('emp_gender', sa.String(length=1), nullable=False),
    sa.Column('emp_email_id', sa.String(length=100), nullable=False),
    sa.Column('emp_contact_no', sa.BigInteger(), nullable=False),
    sa.Column('emp_breif_profile', sa.Text(), nullable=True),
    sa.Column('emp_designation', sa.String(length=50), nullable=False),
    sa.Column('emp_address', sa.Text(), nullable=False),
    sa.Column('emp_photo', sa.String(length=70), nullable=True),
    sa.Column('center_id', sa.Integer(), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.Column('emp_pass', sa.String(length=255), nullable=False),
    sa.Column('emp_last_login', sa.DateTime(), nullable=True),
    sa.Column('emp_role_id', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['center_id'], ['m_center.center_id'], ),
    sa.ForeignKeyConstraint(['district_id'], ['m_district.district_id'], ),
    sa.ForeignKeyConstraint(['emp_role_id'], ['m_role.role_id'], ),
    sa.ForeignKeyConstraint(['state_id'], ['m_state.state_id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['m_employee.employee_id'], ),
    sa.PrimaryKeyConstraint('employee_id')
    )
    op.create_index(op.f('ix_m_employee_emp_email_id'), 'm_employee', ['emp_email_id'], unique=True)
    op.create_index(op.f('ix_m_employee_employee_id'), 'm_employee', ['employee_id'], unique=False)
    op.create_table('m_session',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('session_name', sa.String(length=20), nullable=False),
    sa.Column('session_desc', sa.Text(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('center_id', sa.Integer(), nullable=False),
    sa.Column('active_status', sa.String(length=1), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['center_id'], ['m_center.center_id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['m_employee.employee_id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_m_session_session_id'), 'm_session', ['session_id'], unique=False)
    op.create_table('t_gallery',
    sa.Column('gallery_id', sa.Integer(), nullable=False),
    sa.Column('gal_cat_id', sa.Integer(), nullable=False),
    sa.Column('gal_caption', sa.Text(), nullable=False),
    sa.Column('gal_desc', sa.Text(), nullable=False),
    sa.Column('hyperlink', sa.String(length=10), nullable=True),
    sa.Column('gal_img', sa.String(length=100), nullable=True),
    sa.Column('gal_status', sa.String(length=1), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['gal_cat_id'], ['m_gallery_category.gal_cat_id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['m_employee.employee_id'], ),
    sa.PrimaryKeyConstraint('gallery_id')
    )
    op.create_index(op.f('ix_t_gallery_gallery_id'), 't_gallery', ['gallery_id'], unique=False)
    op.create_table('t_news',
    sa.Column('news_id', sa.Integer(), nullable=False),
    sa.Column('news_cat_id', sa.Integer(), nullable=False),
    sa.Column('news_title', sa.String(length=100), nullable=False),
    sa.Column('news_desc', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=1), nullable=False),
    sa.Column('start_datetime', sa.DateTime(), nullable=False),
    sa.Column('end_datetime', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['news_cat_id'], ['m_news_category.news_cat_id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['m_employee.employee_id'], ),
    sa.PrimaryKeyConstraint('news_id')
    )
    op.create_index(op.f('ix_t_news_news_id'), 't_news', ['news_id'], unique=False)
    op.create_table('t_train_calendar',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('event_title', sa.String(length=100), nullable=False),
    sa.Column('center_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['center_id'], ['m_center.center_id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['m_employee.employee_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_t_train_calendar_event_id'), 't_train_calendar', ['event_id'], unique=False)
    op.create_table('t_enrollment_news',
    sa.Column('enroll_id', sa.Integer(), nullable=False),
    sa.Column('enroll_title', sa.String(length=100), nullable=False),
    sa.Column('enroll_desc', sa.Text(), nullable=False),
    sa.Column('enroll_start_date', sa.DateTime(), nullable=False),
    sa.Column('enroll_end_date', sa.DateTime(), nullable=False),
    sa.Column('center_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=False),
    sa.Column('active_status', sa.String(length=1), nullable=False),
    sa.ForeignKeyConstraint(['center_id'], ['m_center.center_id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['m_session.session_id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['m_employee.employee_id'], ),
    sa.PrimaryKeyConstraint('enroll_id')
    )
    op.create_index(op.f('ix_t_enrollment_news_enroll_id'), 't_enrollment_news', ['enroll_id'], unique=False)
    op.create_table('t_applications',
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('applicant_id', sa.Integer(), nullable=False),
    sa.Column('enroll_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('center_id', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('reg_id', sa.String(length=20), nullable=True),
    sa.Column('applicant_email_id', sa.String(length=100), nullable=False),
    sa.Column('qualification_id', sa.Integer(), nullable=False),
    sa.Column('stream_id', sa.Integer(), nullable=False),
    sa.Column('marks', sa.String(length=5), nullable=False),
    sa.Column('dob_image', sa.String(length=50), nullable=True),
    sa.Column('marksheet_image', sa.String(length=50), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('enrollment_status', sa.String(length=1), nullable=False),
    sa.Column('payment_status', sa.String(length=1), nullable=False),
    sa.Column('cert_status', sa.String(length=1), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=False),
    sa.Column('sel_by', sa.Integer(), nullable=True),
    sa.Column('sel_date', sa.DateTime(), nullable=True),
    sa.Column('transac_det', sa.String(length=20), nullable=True),
    sa.Column('transac_det_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['applicant_id'], ['m_applicant.applicant_id'], ),
    sa.ForeignKeyConstraint(['center_id'], ['m_center.center_id'], ),
    sa.ForeignKeyConstraint(['enroll_id'], ['t_enrollment_news.enroll_id'], ),
    sa.ForeignKeyConstraint(['qualification_id'], ['m_qualification.qualification_id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['m_role.role_id'], ),
    sa.ForeignKeyConstraint(['sel_by'], ['m_employee.employee_id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['m_session.session_id'], ),
    sa.ForeignKeyConstraint(['stream_id'], ['m_stream.stream_id'], ),
    sa.PrimaryKeyConstraint('application_id')
    )
    op.create_index(op.f('ix_t_applications_application_id'), 't_applications', ['application_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_t_applications_application_id'), table_name='t_applications')
    op.drop_table('t_applications')
    op.drop_index(op.f('ix_t_enrollment_news_enroll_id'), table_name='t_enrollment_news')
    op.drop_table('t_enrollment_news')
    op.drop_index(op.f('ix_t_train_calendar_event_id'), table_name='t_train_calendar')
    op.drop_table('t_train_calendar')
    op.drop_index(op.f('ix_t_news_news_id'), table_name='t_news')
    op.drop_table('t_news')
    op.drop_index(op.f('ix_t_gallery_gallery_id'), table_name='t_gallery')
    op.drop_table('t_gallery')
    op.drop_index(op.f('ix_m_session_session_id'), table_name='m_session')
    op.drop_table('m_session')
    op.drop_index(op.f('ix_m_employee_employee_id'), table_name='m_employee')
    op.drop_index(op.f('ix_m_employee_emp_email_id'), table_name='m_employee')
    op.drop_table('m_employee')
    op.drop_index(op.f('ix_m_center_center_id'), table_name='m_center')
    op.drop_table('m_center')
    op.drop_index(op.f('ix_m_applicant_email_id'), table_name='m_applicant')
    op.drop_index(op.f('ix_m_applicant_applicant_id'), table_name='m_applicant')
    op.drop_table('m_applicant')
    op.drop_index(op.f('ix_m_district_district_id'), table_name='m_district')
    op.drop_table('m_district')
    op.drop_index(op.f('ix_m_college_college_id'), table_name='m_college')
    op.drop_table('m_college')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_employee_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_center_id'), table_name='users')
    op.drop_index(op.f('ix_users_applicant_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_user_otp_track_otp_id'), table_name='user_otp_track')
    op.drop_index(op.f('ix_user_otp_track_email'), table_name='user_otp_track')
    op.drop_table('user_otp_track')
    op.drop_index(op.f('ix_m_stream_stream_id'), table_name='m_stream')
    op.drop_table('m_stream')
    op.drop_index(op.f('ix_m_state_state_id'), table_name='m_state')
    op.drop_table('m_state')
    op.drop_index(op.f('ix_m_role_role_id'), table_name='m_role')
    op.drop_table('m_role')
    op.drop_index(op.f('ix_m_qualification_qualification_id'), table_name='m_qualification')
    op.drop_table('m_qualification')
    op.drop_index(op.f('ix_m_news_category_news_cat_id'), table_name='m_news_category')
    op.drop_table('m_news_category')
    op.drop_index(op.f('ix_m_gallery_category_gal_cat_id'), table_name='m_gallery_category')
    op.drop_table('m_gallery_category')
    op.drop_index(op.f('ix_m_caste_caste_id'), table_name='m_caste')
    op.drop_table('m_caste')
    # ### end Alembic commands ###

